logging:
  file:
    name: src/main/resources/eCommerce.log
# For local testing and demo purposes, the MYSQL database configuration has been temporarily disabled,
# and a local in-memory database has been configured
spring:
  jpa:
    # database: MYSQL
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  dataSource:
    #    platform: mysql
    #    url: jdbc:mysql://localhost:3306/mysql
    #    username: root
    #    password: root
    #    driverClassName:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # you can access the console through this link: http://localhost:8080/h2-console
  mvc:
    pathMatch:
      matching-strategy: ant-path-matcher